### PR TITLE
resolves #277 Post request bug correction

### LINKED ISSUE #277: Ruby asciidoctor-kroki Failed to load AsciiDoc document on post request
Launching  the command : 

```
bundle exec asciidoctor -a toc -r asciidoctor-kroki Figures.adoc -D public
```

return 

```
asciidoctor: FAILED: documentation/Figures.adoc: Failed to load AsciiDoc document - undefined method `request_post' for Net::HTTP:Class
```

### PR DESCRIPTION
**Pull request by demagnevalCegelec**
Fix  issue #277 
asciidoctor: FAILED: documentation/Figures.adoc: Failed to load AsciiDoc document - undefined method `request_post' for Net::HTTP:Class

### CODE REVIEW

**Comment by Mogztter** [comment]
Thanks @demagnevalCegelec 
Could you please fix the style issue reported by Rubocop?

Also, I think we should probably test this method using a mock HTTP server. We have a unit test but we do not actually test the `post` method (we only check that the method is called).

File: ruby/lib/asciidoctor/extensions/asciidoctor_kroki/extension.rb [hunk 1]
```diff
@@ -377,7 +377,7 @@ def get(uri, _)
       end
 
       def post(uri, data, _)
-        res = ::Net::HTTP.request_post(uri, data)
+        res = ::Net::HTTP.post(URI(uri), data, "Content-Type" => "text/plain")
```
Comment (Mogztter) [inline ruby/lib/asciidoctor/extensions/asciidoctor_kroki/extension.rb:380]:
```suggestion
        res = ::Net::HTTP.post(URI(uri), data, 'Content-Type' => 'text/plain')
```
